version: '3'

services: 
  redis:
    image: redis:3.2
    container_name: spammer-redis
    ports:
      - 6379:6379
    networks: 
      - app-network

  core:
    depends_on:
      - redis
    build: core/
    container_name: spammer-core
    command: npm start
    environment:
      - PORT=5000
    ports:
      - 5000:5000
    links:
      - redis:redis
    networks: 
      - app-network

  ui:
    build: ui/
    container_name: spammer-ui
    command: npm run serve
    ports:
      - 8080:8080
    networks: 
      - app-network

networks:
  app-network:
    driver: bridge
